// Generated by gencpp from file rokae_jps_navigation/eefStateRequest.msg
// DO NOT EDIT!


#ifndef ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATEREQUEST_H
#define ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokae_jps_navigation
{
template <class ContainerAllocator>
struct eefStateRequest_
{
  typedef eefStateRequest_<ContainerAllocator> Type;

  eefStateRequest_()
    : ifVerbose(false)  {
    }
  eefStateRequest_(const ContainerAllocator& _alloc)
    : ifVerbose(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ifVerbose_type;
  _ifVerbose_type ifVerbose;





  typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct eefStateRequest_

typedef ::rokae_jps_navigation::eefStateRequest_<std::allocator<void> > eefStateRequest;

typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateRequest > eefStateRequestPtr;
typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateRequest const> eefStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator1> & lhs, const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ifVerbose == rhs.ifVerbose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator1> & lhs, const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokae_jps_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67f516a089e3bfc934eaf4bae00ce98e";
  }

  static const char* value(const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67f516a089e3bfc9ULL;
  static const uint64_t static_value2 = 0x34eaf4bae00ce98eULL;
};

template<class ContainerAllocator>
struct DataType< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokae_jps_navigation/eefStateRequest";
  }

  static const char* value(const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ifVerbose\n"
;
  }

  static const char* value(const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ifVerbose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eefStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokae_jps_navigation::eefStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "ifVerbose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ifVerbose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATEREQUEST_H
