// Generated by gencpp from file rokae_jps_navigation/eefStateResponse.msg
// DO NOT EDIT!


#ifndef ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATERESPONSE_H
#define ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rokae_jps_navigation
{
template <class ContainerAllocator>
struct eefStateResponse_
{
  typedef eefStateResponse_<ContainerAllocator> Type;

  eefStateResponse_()
    : eef_pose()  {
    }
  eefStateResponse_(const ContainerAllocator& _alloc)
    : eef_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _eef_pose_type;
  _eef_pose_type eef_pose;





  typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct eefStateResponse_

typedef ::rokae_jps_navigation::eefStateResponse_<std::allocator<void> > eefStateResponse;

typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateResponse > eefStateResponsePtr;
typedef boost::shared_ptr< ::rokae_jps_navigation::eefStateResponse const> eefStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator1> & lhs, const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.eef_pose == rhs.eef_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator1> & lhs, const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokae_jps_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e78f5a947f0283d2ebd6c70bccbefe0";
  }

  static const char* value(const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e78f5a947f0283dULL;
  static const uint64_t static_value2 = 0x2ebd6c70bccbefe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokae_jps_navigation/eefStateResponse";
  }

  static const char* value(const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose eef_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.eef_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eefStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokae_jps_navigation::eefStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "eef_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.eef_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATERESPONSE_H
