// Generated by gencpp from file rokae_jps_navigation/eefState.msg
// DO NOT EDIT!


#ifndef ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATE_H
#define ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATE_H

#include <ros/service_traits.h>


#include <rokae_jps_navigation/eefStateRequest.h>
#include <rokae_jps_navigation/eefStateResponse.h>


namespace rokae_jps_navigation
{

struct eefState
{

typedef eefStateRequest Request;
typedef eefStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct eefState
} // namespace rokae_jps_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokae_jps_navigation::eefState > {
  static const char* value()
  {
    return "dc45c501754cc9c6c2ec61a0d5b19682";
  }

  static const char* value(const ::rokae_jps_navigation::eefState&) { return value(); }
};

template<>
struct DataType< ::rokae_jps_navigation::eefState > {
  static const char* value()
  {
    return "rokae_jps_navigation/eefState";
  }

  static const char* value(const ::rokae_jps_navigation::eefState&) { return value(); }
};


// service_traits::MD5Sum< ::rokae_jps_navigation::eefStateRequest> should match
// service_traits::MD5Sum< ::rokae_jps_navigation::eefState >
template<>
struct MD5Sum< ::rokae_jps_navigation::eefStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokae_jps_navigation::eefState >::value();
  }
  static const char* value(const ::rokae_jps_navigation::eefStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokae_jps_navigation::eefStateRequest> should match
// service_traits::DataType< ::rokae_jps_navigation::eefState >
template<>
struct DataType< ::rokae_jps_navigation::eefStateRequest>
{
  static const char* value()
  {
    return DataType< ::rokae_jps_navigation::eefState >::value();
  }
  static const char* value(const ::rokae_jps_navigation::eefStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokae_jps_navigation::eefStateResponse> should match
// service_traits::MD5Sum< ::rokae_jps_navigation::eefState >
template<>
struct MD5Sum< ::rokae_jps_navigation::eefStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokae_jps_navigation::eefState >::value();
  }
  static const char* value(const ::rokae_jps_navigation::eefStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokae_jps_navigation::eefStateResponse> should match
// service_traits::DataType< ::rokae_jps_navigation::eefState >
template<>
struct DataType< ::rokae_jps_navigation::eefStateResponse>
{
  static const char* value()
  {
    return DataType< ::rokae_jps_navigation::eefState >::value();
  }
  static const char* value(const ::rokae_jps_navigation::eefStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKAE_JPS_NAVIGATION_MESSAGE_EEFSTATE_H
