// Generated by gencpp from file rokae_jps_navigation/Goto.msg
// DO NOT EDIT!


#ifndef ROKAE_JPS_NAVIGATION_MESSAGE_GOTO_H
#define ROKAE_JPS_NAVIGATION_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <rokae_jps_navigation/GotoRequest.h>
#include <rokae_jps_navigation/GotoResponse.h>


namespace rokae_jps_navigation
{

struct Goto
{

typedef GotoRequest Request;
typedef GotoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Goto
} // namespace rokae_jps_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokae_jps_navigation::Goto > {
  static const char* value()
  {
    return "db7c9c254c9a1585396c175f27b28c32";
  }

  static const char* value(const ::rokae_jps_navigation::Goto&) { return value(); }
};

template<>
struct DataType< ::rokae_jps_navigation::Goto > {
  static const char* value()
  {
    return "rokae_jps_navigation/Goto";
  }

  static const char* value(const ::rokae_jps_navigation::Goto&) { return value(); }
};


// service_traits::MD5Sum< ::rokae_jps_navigation::GotoRequest> should match
// service_traits::MD5Sum< ::rokae_jps_navigation::Goto >
template<>
struct MD5Sum< ::rokae_jps_navigation::GotoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokae_jps_navigation::Goto >::value();
  }
  static const char* value(const ::rokae_jps_navigation::GotoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokae_jps_navigation::GotoRequest> should match
// service_traits::DataType< ::rokae_jps_navigation::Goto >
template<>
struct DataType< ::rokae_jps_navigation::GotoRequest>
{
  static const char* value()
  {
    return DataType< ::rokae_jps_navigation::Goto >::value();
  }
  static const char* value(const ::rokae_jps_navigation::GotoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokae_jps_navigation::GotoResponse> should match
// service_traits::MD5Sum< ::rokae_jps_navigation::Goto >
template<>
struct MD5Sum< ::rokae_jps_navigation::GotoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokae_jps_navigation::Goto >::value();
  }
  static const char* value(const ::rokae_jps_navigation::GotoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokae_jps_navigation::GotoResponse> should match
// service_traits::DataType< ::rokae_jps_navigation::Goto >
template<>
struct DataType< ::rokae_jps_navigation::GotoResponse>
{
  static const char* value()
  {
    return DataType< ::rokae_jps_navigation::Goto >::value();
  }
  static const char* value(const ::rokae_jps_navigation::GotoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKAE_JPS_NAVIGATION_MESSAGE_GOTO_H
