// Generated by gencpp from file rokae_jps_navigation/joint2poseResponse.msg
// DO NOT EDIT!


#ifndef ROKAE_JPS_NAVIGATION_MESSAGE_JOINT2POSERESPONSE_H
#define ROKAE_JPS_NAVIGATION_MESSAGE_JOINT2POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rokae_jps_navigation
{
template <class ContainerAllocator>
struct joint2poseResponse_
{
  typedef joint2poseResponse_<ContainerAllocator> Type;

  joint2poseResponse_()
    : re_pose()  {
    }
  joint2poseResponse_(const ContainerAllocator& _alloc)
    : re_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _re_pose_type;
  _re_pose_type re_pose;





  typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct joint2poseResponse_

typedef ::rokae_jps_navigation::joint2poseResponse_<std::allocator<void> > joint2poseResponse;

typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse > joint2poseResponsePtr;
typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse const> joint2poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator1> & lhs, const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.re_pose == rhs.re_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator1> & lhs, const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokae_jps_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "222653e911ec2723bf153c3e2c46d638";
  }

  static const char* value(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x222653e911ec2723ULL;
  static const uint64_t static_value2 = 0xbf153c3e2c46d638ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokae_jps_navigation/joint2poseResponse";
  }

  static const char* value(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose re_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.re_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint2poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "re_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.re_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKAE_JPS_NAVIGATION_MESSAGE_JOINT2POSERESPONSE_H
