// Generated by gencpp from file rokae_jps_navigation/joint2poseResponse.msg
// DO NOT EDIT!


#ifndef ROKAE_JPS_NAVIGATION_MESSAGE_JOINT2POSERESPONSE_H
#define ROKAE_JPS_NAVIGATION_MESSAGE_JOINT2POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokae_jps_navigation
{
template <class ContainerAllocator>
struct joint2poseResponse_
{
  typedef joint2poseResponse_<ContainerAllocator> Type;

  joint2poseResponse_()
    {
    }
  joint2poseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct joint2poseResponse_

typedef ::rokae_jps_navigation::joint2poseResponse_<std::allocator<void> > joint2poseResponse;

typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse > joint2poseResponsePtr;
typedef boost::shared_ptr< ::rokae_jps_navigation::joint2poseResponse const> joint2poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rokae_jps_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokae_jps_navigation/joint2poseResponse";
  }

  static const char* value(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint2poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rokae_jps_navigation::joint2poseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROKAE_JPS_NAVIGATION_MESSAGE_JOINT2POSERESPONSE_H
