// Generated by gencpp from file rokae_arm_toppra/ToppRa_srv.msg
// DO NOT EDIT!


#ifndef ROKAE_ARM_TOPPRA_MESSAGE_TOPPRA_SRV_H
#define ROKAE_ARM_TOPPRA_MESSAGE_TOPPRA_SRV_H

#include <ros/service_traits.h>


#include <rokae_arm_toppra/ToppRa_srvRequest.h>
#include <rokae_arm_toppra/ToppRa_srvResponse.h>


namespace rokae_arm_toppra
{

struct ToppRa_srv
{

typedef ToppRa_srvRequest Request;
typedef ToppRa_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToppRa_srv
} // namespace rokae_arm_toppra


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokae_arm_toppra::ToppRa_srv > {
  static const char* value()
  {
    return "7cd293dc242907880f3bae1412ae9b57";
  }

  static const char* value(const ::rokae_arm_toppra::ToppRa_srv&) { return value(); }
};

template<>
struct DataType< ::rokae_arm_toppra::ToppRa_srv > {
  static const char* value()
  {
    return "rokae_arm_toppra/ToppRa_srv";
  }

  static const char* value(const ::rokae_arm_toppra::ToppRa_srv&) { return value(); }
};


// service_traits::MD5Sum< ::rokae_arm_toppra::ToppRa_srvRequest> should match
// service_traits::MD5Sum< ::rokae_arm_toppra::ToppRa_srv >
template<>
struct MD5Sum< ::rokae_arm_toppra::ToppRa_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokae_arm_toppra::ToppRa_srv >::value();
  }
  static const char* value(const ::rokae_arm_toppra::ToppRa_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokae_arm_toppra::ToppRa_srvRequest> should match
// service_traits::DataType< ::rokae_arm_toppra::ToppRa_srv >
template<>
struct DataType< ::rokae_arm_toppra::ToppRa_srvRequest>
{
  static const char* value()
  {
    return DataType< ::rokae_arm_toppra::ToppRa_srv >::value();
  }
  static const char* value(const ::rokae_arm_toppra::ToppRa_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokae_arm_toppra::ToppRa_srvResponse> should match
// service_traits::MD5Sum< ::rokae_arm_toppra::ToppRa_srv >
template<>
struct MD5Sum< ::rokae_arm_toppra::ToppRa_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokae_arm_toppra::ToppRa_srv >::value();
  }
  static const char* value(const ::rokae_arm_toppra::ToppRa_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokae_arm_toppra::ToppRa_srvResponse> should match
// service_traits::DataType< ::rokae_arm_toppra::ToppRa_srv >
template<>
struct DataType< ::rokae_arm_toppra::ToppRa_srvResponse>
{
  static const char* value()
  {
    return DataType< ::rokae_arm_toppra::ToppRa_srv >::value();
  }
  static const char* value(const ::rokae_arm_toppra::ToppRa_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKAE_ARM_TOPPRA_MESSAGE_TOPPRA_SRV_H
