(cl:in-package rokae_jps_navigation-srv)
(cl:export '(GOAL_POSE-VAL
          GOAL_POSE
          IFBACK-VAL
          IFBACK
          MESSAGE-VAL
          MESSAGE
          SUCCESS-VAL
          SUCCESS
          PX-VAL
          PX
          PY-VAL
          PY
          PZ-VAL
          PZ
          POS-VAL
          POS
          VEL-VAL
          VEL
          ACC-VAL
          ACC
          T-VAL
          T
          BACK_POS-VAL
          BACK_POS
          BACK_VEL-VAL
          BACK_VEL
          BACK_ACC-VAL
          BACK_ACC
          BACK_T-VAL
          BACK_T
))