manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - elerobot_joint0
    - elerobot_joint1
    - elerobot_joint2
    - elerobot_joint3
    - elerobot_joint4
    - elerobot_joint5
  gains:
    elerobot_joint0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elerobot_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elerobot_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elerobot_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elerobot_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elerobot_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1