# # Simulation settings for using moveit_sim_controllers
# moveit_sim_hw_interface:
#   joint_model_group: manipulator
#   joint_model_group_pose: home
# # Settings for ros_control_boilerplate control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - rokae_arm_joint0
#     - rokae_arm_joint1
#     - rokae_arm_joint2
#     - rokae_arm_joint3
#     - rokae_arm_joint4
#     - rokae_arm_joint5
#     - vacuum_joint_1
#     - vacuum_joint_10
#     - vacuum_joint_11
#     - vacuum_joint_12
#     - vacuum_joint_13
#     - vacuum_joint_2
#     - vacuum_joint_3
#     - vacuum_joint_4
#     - vacuum_joint_5
#     - vacuum_joint_6
#     - vacuum_joint_7
#     - vacuum_joint_8
#     - vacuum_joint_9
#   sim_control_mode: 1  # 0: position, 1: velocity
controller_manager_ns: controller_manager
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - elerobot_joint0
      - elerobot_joint1
      - elerobot_joint2
      - elerobot_joint3
      - elerobot_joint4
      - elerobot_joint5