<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="elerobot">

  <!-- module -->
  <xacro:include filename="$(find elerobot_description)/xacro/color.xacro"/>
  <xacro:include filename="$(find elerobot_description)/xacro/property.xacro"/>
  <xacro:include filename="$(find elerobot_description)/xacro/vacuum_group.xacro"/>

  <!-- elephant panda robot p3 type description-->
  <xacro:macro name="elerobot" params="arm_id:='elerobot' with_camera:='false'">
    
    <!-- di435  frame definition can be found at https://github.com/IntelRealSense/librealsense/blob/master/doc/d435i.md -->
    <xacro:if value="${with_camera}">
      <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d435i.urdf.xacro"/>
      <xacro:sensor_d435i  parent="${arm_id}_link7" name="D435i_camera" topics_ns="D435i_camera" enable_pointCloud="true" align_depth="false">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 ${-PI/2} ${PI/2}"/>
      </xacro:sensor_d435i> 
    </xacro:if>

    <!-- LINK DESCRIPTION -->
    <!-- Gazebo requires a joint to a link called "world" for statically mounted robots -->
    <link name="world" />
    <joint name="world_joint" type="fixed">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <parent link="world"/>
      <child link="${arm_id}_link0"/>
    </joint>
    
    <!-- link0 -->
    <link name="${arm_id}_link0">
      <visual>
        <origin xyz="-0.06 -0.06 0.05" rpy="${-PI/2} 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}0${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="-0.06 -0.06 0.05" rpy="${-PI/2} 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}0${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </collision>
      <inertial>
        <origin xyz="-0.0008 0.0091 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${link0_mass}"/>
        <inertia ixx="0.0017" ixy="0.0000" ixz="0.0000" 
                              iyy="0.0028"  iyz="0.0000" 
                                            izz="0.0017"/>
      </inertial>
    </link>

    <!-- link1 -->
    <link name="${arm_id}_link1">
      <visual>
        <origin xyz="-0.0528 -0.0528 -0.07" rpy="0.0 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}1${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="-0.0528 -0.0528 -0.07" rpy="0.0 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}1${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </collision>
      <inertial>
        <origin xyz="0.0 0.0032 0.0615" rpy="0.0 0.0 0.0"/>
        <mass value="${link1_mass}"/>
        <inertia ixx="0.0156" ixy="0.0000" ixz="0.0000" 
                              iyy="0.0154" iyz="0.0004" 
                                           izz="0.0034"/>
      </inertial>
    </link>

    <!-- link2 -->
    <link name="${arm_id}_link2">
      <visual>
        <origin xyz="-0.054 -0.053 0.155" rpy="${-PI/2} 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}2${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="-0.054 -0.053 0.155" rpy="${-PI/2} 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}2${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </collision>
      <inertial>
        <origin xyz="0.0 -0.0049 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${link2_mass}"/>
        <inertia ixx="0.0137" ixy="0.0000" ixz="0.0000" 
                              iyy="0.0940" iyz="0.0000" 
                                           izz="0.0997"/>
      </inertial>
    </link>

    <!-- link3 -->
    <link name="${arm_id}_link3">
      <visual>
        <origin xyz="0.2815 0.078 0.022" rpy="${-PI/2} 0.0 ${PI}"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}3${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0.2815 0.078 0.022" rpy="${-PI/2} 0.0 ${PI}"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}3${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </collision>
      <inertial>
        <origin xyz="0.0052 0.0037 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${link3_mass}"/>
        <inertia ixx="0.0049" ixy="-0.0001" ixz="0.0000" 
                              iyy="0.0446"  iyz="0.0000" 
                                            izz="0.0456"/>
      </inertial>
    </link>

    <!-- link4 -->
    <link name="${arm_id}_link4">
      <visual>
        <origin xyz="-0.0772 -0.055 0.046" rpy="${-PI/2} 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}4${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="-0.0772 -0.055 0.046" rpy="${-PI/2} 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}4${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </collision>
      <inertial>
        <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
        <mass value="${link4_mass}"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0000" 
                              iyy="0.01" iyz="0.0" 
                                         izz="0.0"/>
      </inertial>
    </link>

    <!-- link5 -->
    <link name="${arm_id}_link5">
      <visual>
        <origin xyz="0.0775 0.0605 0.046" rpy="${-PI/2} 0.0 ${PI}"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}5${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin xyz="0.0775 0.0605 0.046" rpy="${-PI/2} 0.0 ${PI}"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}5${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="white"/>
      </collision>
      <inertial>
        <origin xyz="0.0 0.0023 0.0506" rpy="0.0 0.0 0.0"/>
        <mass value="${link5_mass}"/>
        <inertia ixx="0.0059" ixy="0.0" ixz="0.0000" 
                              iyy="0.0059" iyz="0.0002" 
                                         izz="0.0014"/>
      </inertial>
    </link>

    <!-- link6 -->
    <link name="${arm_id}_link6">
      <visual>
        <origin xyz="-0.0425 -0.0425 -0.007" rpy="0.0 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}6${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="-0.0425 -0.0425 -0.007" rpy="0.0 0.0 0.0"/>
        <geometry>
          <mesh filename="${mesh_file_path}${mesh_prefix}6${mesh_suffix}" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="grey"/>
      </collision>
      <inertial>
        <origin xyz="-0.0001 -0.00033 0.02" rpy="0.0 0.0 0.0"/>
        <mass value="${link6_mass}"/>
        <inertia ixx="0.0003" ixy="0.0"    ixz="0.0" 
                              iyy="0.0003" iyz="0.0" 
                                           izz="0.0003"/>
      </inertial>
    </link>

    <link name="${arm_id}_link7">
      <visual>
        <origin xyz="0.0 0.0 ${-link7_h/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${link7_r}" length="${link7_h}"/>
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-link7_h/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="${link7_r}" length="${link7_h}"/>
        </geometry>
      </collision>
      <inertial>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
          <mass value="${link7_mass}"/>
          <xacro:cylinder_inertia m="${link7_mass}" r="${link7_r}" h="${link7_h}"/>
      </inertial>
    </link>

    <!-- JOINT DESCRIPTION -->
    <!-- joint0 Locked -->
    <joint name="${arm_id}_joint0" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="0.0 0.0 ${joint0_z}" rpy="0.0 0.0 0.0"/>
      <!-- <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*0.001/180}" soft_upper_limit="${PI*0.001/180}"/> -->
      <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*360/180}" soft_upper_limit="${PI*360/180}"/>
      <limit acceleration="15" effort="500.0" lower="${-PI*360/180}" upper="${PI*360/180}" velocity="${180/180*PI}"/>
      <parent link="${arm_id}_link0"/>
      <child link="${arm_id}_link1"/>
      <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.01"/>
    </joint>

    <!-- joint1 -->
    <joint name="${arm_id}_joint1" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="0.0 ${joint1_y} 0.0" rpy="0.0 ${-PI/2} ${-PI/2}"/>
      <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*360/180}" soft_upper_limit="${PI*360/180}"/>
      <limit acceleration="15" effort="500.0" lower="${-PI*360/180}" upper="${PI*360/180}" velocity="${180/180*PI}"/>
      <parent link="${arm_id}_link1"/>
      <child link="${arm_id}_link2"/>
      <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.01"/>
    </joint>

    <!-- joint2 -->
    <joint name="${arm_id}_joint2" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="${joint2_x} 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*360/180}" soft_upper_limit="${PI*360/180}"/>
      <limit acceleration="15" effort="500.0" lower="${-PI*360/180}" upper="${PI*360/180}" velocity="${180/180*PI}"/>
      <parent link="${arm_id}_link2"/>
      <child link="${arm_id}_link3"/>
      <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.01"/>
    </joint>

    <!-- joint3 -->
    <joint name="${arm_id}_joint3" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="${joint3_x} 0.0 ${joint3_z}" rpy="0.0 0.0 ${PI/2}"/>
      <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*360/180}" soft_upper_limit="${PI*360/180}"/>
      <limit acceleration="15" effort="500.0" lower="${-PI*360/180}" upper="${PI*360/180}" velocity="${208/180*PI}"/>
      <parent link="${arm_id}_link3"/>
      <child link="${arm_id}_link4"/>
      <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.01"/>
    </joint>

    <!-- joint4 -->
    <joint name="${arm_id}_joint4" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="0.0 ${joint4_y} 0.0" rpy="0.0 ${-PI/2} ${PI/2}"/>
      <!-- <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*0.001/180}" soft_upper_limit="${PI*0.001/180}"/> -->
      <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*360/180}" soft_upper_limit="${PI*360/180}"/>
      <limit acceleration="15" effort="500.0" lower="${-PI*360/180}" upper="${PI*360/180}" velocity="${208/180*PI}"/>
      <parent link="${arm_id}_link4"/>
      <child link="${arm_id}_link5"/>
      <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.01"/>
    </joint>

    <!-- joint5 Locked -->
    <joint name="${arm_id}_joint5" type="revolute">
      <axis xyz="0 0 1"/>
      <origin xyz="0.0 ${joint5_y} 0.0" rpy="${-PI/2} 0.0 0.0"/>
      <safety_controller k_position="50.0" k_velocity="20.0" soft_lower_limit="${-PI*360/180}" soft_upper_limit="${PI*360/180}"/>
      <limit acceleration="15" effort="500.0" lower="${-PI*360/180}" upper="${PI*360/180}" velocity="${208/180*PI}"/>
      <parent link="${arm_id}_link5"/>
      <child link="${arm_id}_link6"/>
      <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.01"/>
    </joint>

    <!-- joint6 -->
    <joint name="${arm_id}_joint6" type="fixed">
      <origin xyz="0.0 0.0 ${joint6_z}" rpy="0.0 0.0 0.0"/>
      <parent link="${arm_id}_link6"/>
      <child link="${arm_id}_link7"/>
    </joint>   
    
    <!-- vacuum gripper -->
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="1" vacuum_x="0"                    vacuum_y="0"                   vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="2" vacuum_x="${vacuum_radius*3}"   vacuum_y="0"                   vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="3" vacuum_x="${-vacuum_radius*3}"  vacuum_y="0"                   vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="4" vacuum_x="0"                    vacuum_y="${vacuum_radius*3}"  vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="5" vacuum_x="0"                    vacuum_y="${-vacuum_radius*3}" vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="6" vacuum_x="${vacuum_radius*6}"   vacuum_y="0"                   vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="7" vacuum_x="${-vacuum_radius*6}"  vacuum_y="0"                   vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="8" vacuum_x="0"                    vacuum_y="${vacuum_radius*6}"  vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="9" vacuum_x="0"                    vacuum_y="${-vacuum_radius*6}" vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="10" vacuum_x="${vacuum_radius*4}"  vacuum_y="${vacuum_radius*4}"  vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="11" vacuum_x="${-vacuum_radius*4}" vacuum_y="${-vacuum_radius*4}" vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="12" vacuum_x="${-vacuum_radius*4}" vacuum_y="${vacuum_radius*4}"  vacuum_z="${vacuum_length/2}"/>
    <xacro:vacuum_group parent_link="${arm_id}_link7" index="13" vacuum_x="${vacuum_radius*4}"  vacuum_y="${-vacuum_radius*4}" vacuum_z="${vacuum_length/2}"/>
 
  </xacro:macro>

</robot>
