<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rokae_arm">
  
  <xacro:macro name="vacuum_group" params="parent_link index vacuum_x vacuum_y vacuum_z">
    <xacro:property name="vacuum_gripper" value="vacuum_gripper_${index}"/>
    <xacro:property name="gripper_joint" value="vacuum_joint_${index}"/>

    <link name="${vacuum_gripper}">
      <gravity>0</gravity>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-vacuum_length/2}"/>
        <geometry>
          <cylinder radius="${vacuum_radius}" length="${vacuum_length}"/>
        </geometry>
        <material name="transparent">
          <color rgba="255 255 255 0.8"/>
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-vacuum_length/2}"/>
        <geometry>
          <cylinder radius="${vacuum_radius}" length="${vacuum_length/10}"/>
        </geometry>
        <material name="transparent">
          <color rgba="255 255 255 0.8"/>
        </material>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.000000 0.000000 0.000000"/>
        <mass value="0.0001"/>
        <inertia ixx="1e-08" ixy="0" ixz="0" iyy="1e-08" iyz="0" izz="1e-08"/>
      </inertial>
    </link>
    
    <joint name="${gripper_joint}" type="revolute">
      <axis xyz="0 0 1" />
      <parent link="${parent_link}" />
      <child link="${vacuum_gripper}" />
      <origin rpy="0 0 0" xyz="${vacuum_x} ${vacuum_y} ${vacuum_z}" />
      <limit effort="50" velocity="50" lower="0" upper="0" />
      <dynamics damping="0.0" friction="10"/>
    </joint>
 
    <gazebo>
      <plugin name="gazebo_ros_vacuum_gripper_${index}" filename="libgazebo_ros_vacuum_gripper.so">
        <robotNamespace>/rokae_arm/${vacuum_gripper}</robotNamespace>
        <bodyName>${vacuum_gripper}</bodyName>
        <topicName>grasping_${index}</topicName>
        <maxForce>100</maxForce>
        <maxDistance>0.05</maxDistance>
        <minDistance>0.01</minDistance>
      </plugin>
    </gazebo>
    
  </xacro:macro>
</robot>